criaturas = [
    {"name": "Ceto",                   "defeated_by": None},
    {"name": "Tifón",                  "defeated_by": "Zeus"},
    {"name": "Equidna",                "defeated_by": "Argos Panoptes"},
    {"name": "Dino",                   "defeated_by": None},
    {"name": "Pefredo",                "defeated_by": None},
    {"name": "Enio",                   "defeated_by": None},
    {"name": "Escila",                 "defeated_by": None},
    {"name": "Caribdis",               "defeated_by": None},
    {"name": "Euríale",                "defeated_by": None},
    {"name": "Esteno",                 "defeated_by": None},
    {"name": "Medusa",                 "defeated_by": "Perseo"},
    {"name": "Ladón",                  "defeated_by": "Heracles"},
    {"name": "Águila del Cáucaso",     "defeated_by": None},
    {"name": "Quimera",                "defeated_by": "Belerofonte"},
    {"name": "Hidra de Lerna",         "defeated_by": "Heracles"},
    {"name": "León de Nemea",          "defeated_by": "Heracles"},
    {"name": "Esfinge",                "defeated_by": "Edipo"},
    {"name": "Dragón de la Cólquida",  "defeated_by": None},
    {"name": "Cerbero",                "defeated_by": None},
    {"name": "Cerda de Cromión",       "defeated_by": "Teseo"},
    {"name": "Ortro",                  "defeated_by": "Heracles"},
    {"name": "Toro de Creta",          "defeated_by": "Teseo"},
    {"name": "Jabalí de Calidón",      "defeated_by": "Atalanta"},
    {"name": "Carcinos",               "defeated_by": None},
    {"name": "Gerión",                 "defeated_by": "Heracles"},
    {"name": "Cloto",                  "defeated_by": None},
    {"name": "Láquesis",               "defeated_by": None},
    {"name": "Átropos",                "defeated_by": None},
    {"name": "Minotauro de Creta",     "defeated_by": "Teseo"},
    {"name": "Harpías",                "defeated_by": None},
    {"name": "Argos Panoptes",         "defeated_by": "Hermes"},
    {"name": "Aves del Estínfalo",     "defeated_by": None},
    {"name": "Talos",                  "defeated_by": "Medea"},
    {"name": "Sirenas",                "defeated_by": None},
    {"name": "Pitón",                  "defeated_by": "Apolo"},
    {"name": "Cierva de Cerinea",      "defeated_by": None},
    {"name": "Basilisco",              "defeated_by": None},
    {"name": "Jabalí de Erimanto",     "defeated_by": None},
]
